name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.20'

  #   - name: Build
  #     run: go build -v ./...

  #   - name: Test
  #     run: go test -v ./...

  deploy:
      # needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run command on remote server
          uses: kostya-ten/ssh-server-deploy@v4
          with:
            host: ${{ secrets.SERVER_HOST }}
            port: ${{ secrets.SERVER_PORT }}
            username: ${{ secrets.SERVER_USERNAME }}
            private_key: ${{ secrets.PRIVATE_KEY }}
            scp_target: /home/pdf_search
            before_script: | 
              git checkout main;
              git pull;
              docker compose down;
              docker compose up --build -d;
              docker system prune --all --force;
